In [7]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print("test if none of the elements is said array to zero:")
print(np.all(a))
b=np.array([0,1,2,3,4])
print(b)
print("test if none of the elements is said array to zero:")
print(np.all(b))

[1 2 3 4]
test if none of the elements is said array to zero:
True
[0 1 2 3 4]
test if none of the elements is said array to zero:
False


In [10]:
import numpy as np
print(np.__version__)
print(np.show_config())
import numpy as np
print(np.info(np.add))

1.20.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/vinay/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/vinay/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/vinay/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/vinay/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/vinay/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/vinay/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/vinay/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/vinay/anaconda3\\Library\\include']
None
add(x1, x2, /, out=None, *, where=True, 

In [18]:
import numpy as np
a=np.array([0,0,0,0])
print(a)
print("test if none of the elements is said array to non-zero:")
print(np.any(a))
import numpy as np
b=np.array([0,1,1,1])
print(b)
print("test if none of the elements is said array to zero:")
print(np.any(b))

[0 0 0 0]
test if none of the elements is said array to non-zero:
False
[0 1 1 1]
test if none of the elements is said array to zero:
True


In [1]:
import numpy as np
x=np.array([0,1,2,np.inf,np.nan])
print(x)
print("test a given array element wise for finiteness:")
print(np.isfinite(x))
print(np.isinf(x))
print(np.isnan(x))

[ 0.  1.  2. inf nan]
test a given array element wise for finiteness:
[ True  True  True False False]
[False False False  True False]
[False False False False  True]


In [23]:
import numpy as np
x=np.array([0,1,2,np.inf,np.nan])
print(x)
print("test a given array element wise for infiniteness:")
print(np.isinf(x))

[ 0.  1.  2. inf nan]
test a given array element wise for finiteness:
[False False False  True False]


In [26]:
import numpy as np
x=np.array([0,1,2,np.inf,np.nan])
print(x)
print("test a given array element wise for finiteness:")
print(np.isnan(x))

[ 0.  1.  2. inf nan]
test a given array element wise for finiteness:
[False False False False  True]


In [37]:
import numpy as np
x=np.array([0,2,4,6,7+3j,9])
print(x)
print(np.iscomplex(x))
print(np.isreal(x))
print(np.isscalar(3+x))

[0.+0.j 2.+0.j 4.+0.j 6.+0.j 7.+3.j 9.+0.j]
[False False False False  True False]
[ True  True  True  True False  True]
False


In [1]:
#Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.
import numpy as np
print("Test if two arrays are element-wise equal within a tolerance:")
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))


Test if two arrays are element-wise equal within a tolerance:
False
True
False
False
True


In [4]:
#Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.
import numpy as np
x = np.array([1,3])
y = np.array([4,2])
print(x)
print(y)
print(np.greater(x,y))
print(np.greater_equal(x,y))
print(np.less(x,y))
print(np.less_equal(x,y))

[1 3]
[4 2]
[False  True]
[False  True]
[ True False]
[ True False]


In [8]:
#Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays
import numpy as np
x = np.array([0,12,-5,86,2])
y = np.array([86,3526,55,-33,2])
print(x)
print(y)
print(np.equal(x,y))
print(np.allclose(x,y))

[ 0 12 -5 86  2]
[  86 3526   55  -33    2]
[False False False False  True]
False


In [2]:
import numpy as np
x = np.array([1,7,13,105])
print(x)
print("size of the array")
print("%d bytes"%(x.itemsize))

[  1   7  13 105]
size of the array
4 bytes


In [2]:
import numpy as np
array=np.zeros(10)
print(array)
array=np.ones(10)*1
print(array)
array=np.ones(10)*5
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [6]:
import numpy as np
array=np.arange(30,71)
print("arrrangement of the integers:")
print(array)

arrrangement of the integers:
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [9]:
import numpy as np
array=np.arange(30,71,13)
print("arrangement of the even positive integers:")
print(array)

arrangement of the even positive integers:
[30 43 56 69]


In [10]:
#identity matrix
import numpy as np
array_2D=np.identity(3)
print("3x3 matrix:")
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
import numpy as np
rand_num=np.random.normal(0,1,1)
print("print number between 0 and 1:")
print(rand_num)

print number between 0 and 1:
6.808687286371068


In [15]:
import numpy as np
rand_num=np.random.normal(0,1,15)
print("random numbers:")
print(rand_num)

random numbers:
[ 0.51526074  0.74587644 -1.62548846  0.01238571 -1.61105549  0.44598299
  0.30866472  0.74504301  1.42130311 -1.88930148 -0.33494654  0.6529943
 -0.47504261  0.03461138  1.0849316 ]


In [17]:
import numpy as np
v=np.arange(15,55)
print(v)
print("except first and last:")
print(v[1:-1])

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
except first and last:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [21]:
import numpy as np
a=np.arange(10,22).reshape((3x4))
print(a)
print("each element of the array:")
for x in np.nditer(a):
    print(x,end="")


SyntaxError: invalid syntax (Temp/ipykernel_404/2256383353.py, line 2)