In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
l1=[1,2,3]
l2=[4,5,6]
l3=[7,8,9]
a2=np.array([l1,l2,l3])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
a3=np.arange(9)
print(a3)

[0 1 2 3 4 5 6 7 8]


In [6]:
print(a3.reshape(3,3))
print(a3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [7]:
print(a3.resize(3,3))
print(a3)

None
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [35]:
a4=np.arange(2,20,2)
print(a4)

[ 2  4  6  8 10 12 14 16 18]


In [36]:
a4.shape=(3,3)
print(a4)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [37]:
print(a4.ndim)
print(a4.shape)
print(a4.size)
print(a4.itemsize)
print(a4.dtype)
print(a4.data)

2
(3, 3)
9
4
int32


In [11]:
type(a4)

numpy.ndarray

In [12]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
print(np.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
print(np.empty((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [39]:
print(np.linspace(0,10,3))

[ 0.  5. 10.]


In [40]:
print(a)

[1 2 3]


In [17]:
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
print(np.sum(a))
print(np.sum(a1))

6
45


In [41]:

print(np.sum(a1,axis=0))

[12 15 18]


In [20]:
print(np.sum(a1,axis=1))

[ 6 15 24]


In [21]:
import numpy as np

In [22]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [23]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
arr.trace()

15